#!/bin/sh

# Get the best audio, convert it to MP3, and save it to the current
# directory.

if [[ $# == 0 ]]; then
   exit 0
fi

youtube-dl --default-search=ytsearch: \
         --restrict-filenames \
         --format=bestaudio \
         --extract-audio \
         --audio-format=mp3 \
         --audio-quality=1 "$*" && mv *.mp3 \
         ~/Google\ Drive/Pfosi\'s\ Music\ Folder/
