#!/bin/bash

if [ -n "$WP" ]; then
   (
   # TODO: We should not need to install zsh
      a4 yum install -y --enablerepo="*" zsh &
      a4 yum install -y --enablerepo="*" tmux &
      a4 yum install -y --enablerepo="*" mailx &
      a4 yum install -y --enablerepo="*" python-pip &
      a4 yum install -y --enablerepo="*" python-ipdb &
      a4 yum install -y Artacc &
      a4 yum install -y git &

      wait
   ) &> /dev/null

   sudo pip install pycscope

   cd /src
   if [ ! -f .gitignore ]; then
      git a init
   fi

   nohup /home/$USER/.a4c/setupWs.sh &> /dev/null
fi
