#!/bin/bash

if [ -n "$WP" ]; then
   (
      a4 yum install -y --enablerepo="*" zsh tmux mailx python-pip python-ipdb \
      Artacc git mts-cli bc ArTacLSP &

      wait

      # sudo pip install pycscope &
      # sudo pip install isort &
      arsudo pip install -qqq python-language-server
   ) &> /dev/null

   # Don't do this for Gitarband workspaces
   if [ ! -d /src/.repo ]; then
      cd /src
      if [ ! -f .gitignore ]; then
         git a init
      fi
   fi


   nohup /home/$USER/.a4c/setupWs.sh &> /dev/null
fi
